From docker.io/centos:latest
MAINTAINER levon sportshao@163.com
ADD redis-3.2.11.tar.gz /usr/local/
ADD redis_7006.conf /home/redis/7006/conf/redis_7006.conf
ADD install_redis.sh /tmp/install_redis.sh
RUN sh /tmp/install_redis.sh
#ADD redis_7006.conf /home/redis/7006/conf
